// Code generated by protoc-gen-go.
// source: route.proto
// DO NOT EDIT!

package interfaces

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Route struct {
	Id               *string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Path             *string `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	Domain           *string `protobuf:"bytes,4,opt,name=domain" json:"domain,omitempty"`
	Description      *string `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Name             *string `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}

func (m *Route) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Route) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *Route) GetDomain() string {
	if m != nil && m.Domain != nil {
		return *m.Domain
	}
	return ""
}

func (m *Route) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *Route) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func init() {
}
