// Code generated by protoc-gen-go.
// source: route.proto
// DO NOT EDIT!

package interfaces

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Route struct {
	Do               *DO     `protobuf:"varint,1,req,name=do,enum=interfaces.DO" json:"do,omitempty"`
	Id               *string `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	Label            *string `protobuf:"bytes,3,req,name=label" json:"label,omitempty"`
	Path             *string `protobuf:"bytes,4,req,name=path" json:"path,omitempty"`
	Prefix           *string `protobuf:"bytes,5,req,name=prefix" json:"prefix,omitempty"`
	Domain           *string `protobuf:"bytes,6,req,name=domain" json:"domain,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}

func (m *Route) GetDo() DO {
	if m != nil && m.Do != nil {
		return *m.Do
	}
	return DO_UPDATE
}

func (m *Route) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Route) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *Route) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *Route) GetPrefix() string {
	if m != nil && m.Prefix != nil {
		return *m.Prefix
	}
	return ""
}

func (m *Route) GetDomain() string {
	if m != nil && m.Domain != nil {
		return *m.Domain
	}
	return ""
}

func init() {
}
